volumes:
  ignore:
version: '3.8'
services:
  train-mnist:
    build:
      context: .
      dockerfile: Dockerfile
    ipc: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - source: .
        target: /root/workdir
        type: bind
    tty: true
  streamlit-mnist:
    build:
      context: .
      dockerfile: DockerfileApp
    image: streamlit-mnist
    ports:
      - "8501:8501"
    volumes:
      - source: .
        target: /root/app
        type: bind
    tty: true
